name: 'Get Project Configuration'
description: 'Get project configuration from Makefile'
outputs:
  python-versions:
    description: 'JSON array of Python versions'
    value: ${{ steps.config.outputs.python-versions }}
  default-python-version:
    description: 'Default Python version'
    value: ${{ steps.config.outputs.default-python-version }}
  container-registry:
    description: 'Container registry'
    value: ${{ steps.config.outputs.container-registry }}
  container-image:
    description: 'Container image name'
    value: ${{ steps.config.outputs.container-image }}
  package-version:
    description: 'Single version format compatible with PyPI packages, Docker tags, and Git tags'
    value: ${{ steps.config.outputs.package-version }}
  is-release:
    description: 'Whether this is a release build'
    value: ${{ steps.config.outputs.is-release }}
runs:
  using: 'composite'
  steps:
    - name: Install yq
      uses: mikefarah/yq@master

    - name: Get configuration from project config
      id: config
      shell: bash
      run: |
        DEFAULT_PYTHON_VERSION=$(yq '.python.default_version' .project.yml)
        PYTHON_VERSIONS=$(yq -o json '.python.versions' .project.yml | tr -d '\n')
        CONTAINER_REGISTRY=$(yq '.repository.registry // "ghcr.io"' .project.yml)
        REPO_ORG=$(yq '.repository.org' .project.yml)
        REPO_NAME=$(yq '.repository.name' .project.yml)
        CONTAINER_IMAGE="$REPO_ORG/$REPO_NAME"
        
        # Centralized version generation using Makefile infrastructure
        if [[ "${{ github.event_name }}" == "release" ]] || [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.environment }}" == "pypi" ]]; then
          # Explicit release triggers
          PACKAGE_VERSION=$(IS_RELEASE=true make -s get-version)
          IS_RELEASE="true"
        elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
          # Intelligent version detection: compare against last successful release
          CURRENT_VERSION=$(yq '.project.version' .project.yml)
          LAST_RELEASED_VERSION=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' 2>/dev/null | sed 's/^v//' || echo "none")
          
          if [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && [[ "$CURRENT_VERSION" != "$LAST_RELEASED_VERSION" ]]; then
            # Stable version that differs from last release - treat as release
            PACKAGE_VERSION=$(IS_RELEASE=true make -s get-version)
            IS_RELEASE="true"
          else
            # Pre-release version or already released - treat as development
            PACKAGE_VERSION=$(make -s get-version)
            IS_RELEASE="false"
          fi
        else
          # Development build
          PACKAGE_VERSION=$(make -s get-version)
          IS_RELEASE="false"
        fi
        
        {
          echo "default-python-version=$DEFAULT_PYTHON_VERSION"
          echo "python-versions=$PYTHON_VERSIONS"
          echo "container-registry=$CONTAINER_REGISTRY"
          echo "container-image=$CONTAINER_IMAGE"
          echo "package-version=$PACKAGE_VERSION"
          echo "is-release=$IS_RELEASE"
        } >> "$GITHUB_OUTPUT"
        
        echo "Default Python version: $DEFAULT_PYTHON_VERSION"
        echo "Python versions: $PYTHON_VERSIONS"
        echo "Container registry: $CONTAINER_REGISTRY"
        echo "Container image: $CONTAINER_IMAGE"
        echo "Package version: $PACKAGE_VERSION"
        echo "Is release: $IS_RELEASE"
