# Project Configuration
# This file centralizes all project metadata and build settings
# Single source of truth for versions, names, and build parameters

project:
  name: open-resource-broker
  short_name: orb # CLI command name
  version: 0.2.3
  description: "Cloud provider integration plugin for IBM Spectrum Symphony Host Factory"
  author: "AWS Professional Services"
  email: "aws-proserve@amazon.com"
  license: "Apache-2.0"
python:
  versions: ["3.10", "3.11", "3.12", "3.13", "3.14"] # Supported Python versions
  default_version: 3.13
repository:
  org: awslabs
  name: open-resource-broker
  registry: ghcr.io # Container registry
build:
  platforms: [linux/amd64, linux/arm64] # Container platforms
ci:
  test_timeout: 300 # Test timeout in seconds
  coverage_threshold: 70 # Minimum coverage percentage
development:
  pre_commit_enabled: true
  security_scan_enabled: true
